export const data = [
  {
    id: 1,
    title: "Python: Zero to Hero",
    desc: "A perfect Course for beginners to learn Python Programming from Scratch",
    educator: "A. Martin",
    reviews: "1,867",
    ratings: "4.6",
    price: "3999",
    category: "Python",
  },
  {
    id: 2,
    title: "JavaScript: For Beginners",
    desc: "A perfect Course for beginners to learn JavaScript Programming from Scratch",
    educator: "M. John",
    reviews: "1,900",
    ratings: "4.6",
    price: "4999",
    category: "JavaScript",
  },
  {
    id: 3,
    title: "Java Tutorial",
    desc: "A perfect Course for beginners to learn Java Programming from Scratch",
    educator: "John Luther",
    reviews: "1,167",
    ratings: "4.6",
    price: "2999",
    category: "Java",
  },
  {
    id: 4,
    title: "Web Development",
    desc: "A perfect Web Development Course for beginners to learn how to build a website from scratch",
    educator: "Piyush Kesarwani",
    reviews: "700",
    ratings: "4.6",
    price: "4999",
    category: "Web Development",
  },
  {
    id: 5,
    title: "Data Structure and Algorithm",
    desc: "A perfect Course to learn Competitive Programming.",
    educator: "J. Martin",
    reviews: "4,679",
    ratings: "4.6",
    price: "4399",
    category: "DSA",
  },
  {
    id: 6,
    title: "Data Science",
    desc: "A perfect Data Science Course for absolute Beginners",
    educator: "Andrew Lincoln",
    reviews: "1,067",
    ratings: "4.6",
    price: "5999",
    category: "Data Science",
  },
  {
    id: 7,
    title: "AWS: ",
    desc: "An AWS Course for absolute beginner",
    educator: "John Marteni",
    reviews: "1,400",
    ratings: "4.6",
    price: "2999",
    category: "Amazon AWS",
  },
  {
    id: 8,
    title: "HTML/CSS Course",
    desc: "A perfect HTML/CSS Course for beginners",
    educator: "H. King",
    reviews: "3,424",
    ratings: "4.6",
    price: "4899",
    category: "Web Development",
  },
  {
    id: 9,
    title: "Machine Learning",
    desc: "A perfect Machine Learning Course for absolute beginners.",
    educator: "J. Lupin",
    reviews: "4,570",
    ratings: "4.6",
    price: "4999",
    category: "Machine Learning",
  },
];
